### ISSUE TITLE
Option to set VISCA ID

### ISSUE THREAD

**Issue by HugoPlaisier** [bitfocus/companion-module-datavideo-visca#2]
I have multiple PTZ camera's using their own unique VISCA ID's, this because of the RS232 controller I use. 
The current datavideo visca module is set to  VISCA ID 1 per default. It would be very help helpfull when I can set the Visca ID in the same screen where I need to provide the IP and port nr..

**Comment by RoseOO** [comment]
Will look into this later in the month. Should not be too hard to implement.

Closing as it's a duplicate, please follow the other issue.
