### ISSUE TITLE
Custom Commands not functioning

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-datavideo-visca#5]
The custom commands have stopped working with a recent update. The custom command is required to start with an 8(x) which sets the address of the camera, I think the recent update to add the device address now means an 8(x) is automatically added in front of the custom command meaning that it is double addressed ie 8(x) 8(x). Removing the requirement to start the custom command with an 8 should fix the issue.

Thanks Jonathan

**Comment by RoseOO** [comment]
Hi @Jonhug82 I've removed the check in ddba136

I'll ask for it to be updated in the builds.
